server:
  port: 8080
mybatis:
  mapper-locations:
  - classpath:mybatis/*.xml
  - classpath:mybatis/*/*.xml
sensitive-bye:
  mybatis:
    enabled: true
  log:
    enabled: true
password: '******'
test: 123
